### ISSUE TITLE
unable to right click a condition to have it full-size overlay on token icon.

### ISSUE THREAD

**Issue by RulyTafzil** [trdischat/conditions5e#3]
With the default conditions, you can left click to have a small icon appear on the token, or right click to have a full size icon appear on the token.

With this mod, right clicking a condition causes it to briefly flicker as full size on the token then disappear.

Is this intentional since you automatically put full size conditions on the token at certain events? like taking damage, death?

**Comment by BuggStream** [comment]
Why was this issue closed? I have the same issue. I think it is useful to overlay certain conditions on the full size of the token, such that it is harder to overlook them while DMing.

**Comment by trdischat** [comment]
Thanks for you interest, BuggStream.  Unfortunately, the whole point of this module was to use the overlay exclusively to display whether a token is severely injured, unconscious, or dead.  If you want to use the overlay for something else, you shouldn't use this module.  CUB is better suited for your use case.  Moreover, CUB has taken the management of the condition icons so much further now that my module is really redundant at this point.  I made the decision a little while ago to suspend further development.  So it should no longer appear in the list of available modules in foundry.

**Comment by BuggStream** [comment]
> Thanks for you interest, BuggStream. Unfortunately, the whole point of this module was to use the overlay exclusively to display whether a token is severely injured, unconscious, or dead. If you want to use the overlay for something else, you shouldn't use this module. CUB is better suited for your use case. Moreover, CUB has taken the management of the condition icons so much further now that my module is really redundant at this point. I made the decision a little while ago to suspend further development. So it should no longer appear in the list of available modules in foundry.

Thanks for the honesty and for recommending an alternative! This helped me out a lot.
