### ISSUE TITLE
Feature Request: Add tooltips

### ISSUE THREAD

**Issue by kamcknig** [trdischat/conditions5e#4]
Could you add tooltips on hover of the icons?? Thanks!

**Comment by trdischat** [comment]
Thanks for the suggestion.  I will consider it.  But [Combat Utility Belt](https://github.com/death-save/combat-utility-belt) already does tooltips on the condition icons, and I generally prefer to work on features that are not already implemented in someone else's module.  Have you tried CUB?

**Comment by kamcknig** [comment]
> Thanks for the suggestion. I will consider it. But [Combat Utility Belt](https://github.com/death-save/combat-utility-belt) already does tooltips on the condition icons, and I generally prefer to work on features that are not already implemented in someone else's module. Have you tried CUB?

I do have it but I did not see that option, I'll have to take another look thank you

**Comment by geoidesic** [comment]
@trdischat  This library doesn't integrate with CUB well. When you use the two together you get a double set of icons; one with tooltips and one without.

**Comment by trdischat** [comment]
As noted in the descriptions for this module and CUB, these two modules conflict.  Don’t try to use both.
