### ISSUE TITLE
Targeting not being displayed

### ISSUE THREAD

**Issue by Jonwh25** [trdischat/conditions5e#5]
Noticed that when I have this enabled, the targeting is not being displayed.  It sometimes shows and sometimes doesn't.

**Comment by trdischat** [comment]
I am not seeing this behavior.  Can you tell what sequence of events turns off the targeting? What versions of FVTT and conditions5e are you running?  Do you have ALL other modules disabled?

**Comment by Jonwh25** [comment]
You can close this. Was a different module. Thanks for your patience.
