### ISSUE TITLE
I Can't find it

### ISSUE THREAD

**Issue by brunocalado** [trdischat/conditions5e#7]
I can't find it on the Add-ons Module. 

I can only install it through the link.

![image](https://user-images.githubusercontent.com/4999783/87249969-82ce6b00-c438-11ea-8949-8b4398c0f34b.png)

**Comment by trdischat** [comment]
This is not an issue with the module.  If there is a problem, it is with the foundry website.  FWIW, the module shows up in my copy of FVTT without a problem.  In the picture above, you are searching for the word "Critical", which does not appear in the name of this module.  Try "Conditions" instead.
