### ISSUE TITLE
keep all conditions and restore "big" overlay

### ISSUE THREAD

**Issue by cojoMan** [trdischat/conditions5e#8]
- I used a lot of the old "odd" icons for conditions from spells or just to remember stuff, like which one of the goblins is the one with 250hp, elite, etc. Can we have those back ? The current ones are ok, but maybe have a setting to add the old ones as well ?

- before, when you were trying to put a condition marker on a token, normal click would put a small icon upper left, RIGHT CLICK would put an overlay on the token, more easily marking which token is asleep/tied up/etc. With this module enabled, only small icon overlays seem to be allowed. I am just guessing that is because of the "bloodied" overlay that happens based on current HP. I love the bloodied overlay and I want to keep it, but I also want the option for the big overlay "other condition". Any ideas on that ? 

thanks.

**Comment by trdischat** [comment]
Have you tried CUB? It should work for your use case.
